### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Kr4k3n10rd** [UltraBlackLinux/noHurtCam#2]
**Is your feature request related to a problem? Please describe.**
Yes, the hurtcam is enabled by default whenever I join a world.
**Describe the solution you'd like**
I would like it to be disabled when I join automatically, if I have toggled it off in the future.
**Describe alternatives you've considered**
A config screen (?) simply to easily change this kind of setting.
**Additional context**

**Comment by UltraBlackLinux** [comment]
A config screen would take libraries and stuff, it's just impractical for one feature.
If you disable the hurtcam once, it stays off until you restart your game
 ... It's not that bad
